/**创建用户表**/
CREATE TABLE USER (
  ID       INT PRIMARY KEY,
  USERNAME VARCHAR(50),
  PASSWORD VARCHAR(50)
);
/**创建权限表**/
CREATE TABLE AUTHENTICATION (
  ID        INT PRIMARY KEY,
  USER_ID   INT,
  MODULE_ID INT
);
/**模块**/
CREATE TABLE MODULE (
  ID           INT PRIMARY KEY,
  PARENT_ID    INT,
  RANK         INT,
  NAME         VARCHAR(50),
  IDENTIFIER   VARCHAR(20),
  LINK_ADDRESS VARCHAR(200),
  ENABLE INT
);